trigger:          # Indicates when to start this pipeline; 'None' can also be specified
  - main          # main indicates to start the pipeline when code is pushed in to main branch

pool:
  vmImage: ubuntu-latest

stages:
  - stage: FirstBuildStage
    displayName: First Build Stage
    jobs:
      - job: FirstBuildJob
        displayName: First Build Job
        steps:
          - script: echo "This is your first yaml pipeline"
            displayName: echo step

